desc all_catalog ;


4/
 SELECT * FROM DICT WHERE TABLE_NAME LIKE 'USER%' ; 

 SELECT OWNER FROM  ALL_CATALOG GROUP BY OWNER;
 select * from all_catalog where table_name = 'ALL_TABLES';

SELECT OWNER FROM  ALL_CATALOG GROUP BY OWNER;
select * from all_catalog where OWNER = 'AIR3_9';

SELECT * FROM  ALL_CATALOG WHERE OWNER = 'AIR3_9';

// C EST OBLIGATOIREMENT L UTILISATEUR COURNT
3. SELECT * FROM  USER_OBJECTS ;
 DESC USER_OBJECTS ;
SELECT TABLE_NAME FROM ALL_CATALOG WHERE OWNER = 'AIR3_9' ; 
DESC USER_TAB_COLUMNS ;
 DESC ALL_CONSTRAINTS ;

4. SELECT CONSTRAINT_NAME, STATUS FROM ALL_CONSTRAINTS WHERE OWNER = 'AIR3_9' ;

5. DESC USER_USERS ;
 SELECT * FROM USER_USERS ;

6.SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'HAMON' ;


7. SELECT * FROM DBA_TABLESPACES ;







5/ OBJETS ORACLE :

SELECT INSTANCE_NAME, VERSION, HOST_NAME, STATUS FROM v$instance ;
SELECT NAME, OPEN_MODE FROM v$database ;
SELECT NAME FROM v$parameter ;

SELECT * FROM v$logfile ;
SELECT FILE#, BYTES FROM V$datafile ;

 SELECT NAME, TS# FROM v$tablespace ;

select FILE_NAME,TABLESPACE_NAME from DBA_DATA_FILES;


SELECT * FROM DBA_USERS ;
SELECT USER_ID, CREATED, DEFAULT_TABLESPACE FROM USER_USERS ;
SELECT USER_ID, CREATED, DEFAULT_TABLESPACE FROM DBA_USERS ;


SELECT USERNAME, COUNT(*) FROM V$SESSION GROUP BY USERNAME ;
SELECT COUNT(*) FROM v$TRANSACTION NATURAL JOIN V$SESSION ;

















